name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with: 
          file: ./web/Dockerfile
          context: ./web/
          push: true
          tags: |
            otaviomartins/desafio-devops:latest
            otaviomartins/desafio-devops:${{github.run_number}}
            
            
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Docker Compose up
        run: python3 manage.py runserver 0.0.0.0:5000
            
            
            
